### ISSUE TITLE
Missing file in CMakeLists.txt

### ISSUE THREAD

**Issue by matt-frey** [AMReX-Codes/amrex#66]
The file ```AMReX_MultiFabUtil_F.H``` is missing in ```Base/CMakeLists.txt```.

branch: master

Best,
Matthias

**Comment by mic84** [comment]
Working on it

**Comment by matt-frey** [comment]
Thanks.

**Comment by mic84** [comment]
@matt-frey  please try mr-cmake branch: the problem should be fixed now.

**Comment by matt-frey** [comment]
I tried with that branch. The file ```AMReX_MultiFabUtil_F.H``` is still not copied to the install directory.

Furthermore, I have a question regarding the libraries:
It normally builds following static libraries: ```libcboxlib.a, libfboxlib.a, libbox_camrdata.a, libcfboxlib.a```
With that branch I only got the ```libamrex.a``` library. Should this be the case?

If so, one would also need to remove those in ```Tools/CMake/FindCCSE.cmake```

**Comment by mic84** [comment]
Try now. It should work. As far as FindCCSE is concerned, it will be removed soon. We now provide a cmake config file, called AMReXConfig.cmake, installed under /path/to/amrex/install/cmake. In your CMakeLists.txt, use the following command: 
**find_package (AMReX CONFIG REQUIRED HINTS /path/to/amrex/install/cmake )**

This command will load cmake variables with all the info needed for linking amrex to your code code. Please check /path/to/amrex/install/cmake/AMReXConfig.cmake for a full list of all the variables provided.

**Comment by matt-frey** [comment]
Works fine now! Thanks a lot.

Best,
Matthias
